<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Costina.Core.Domain/Costina.Core.Domain.csproj" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <EmbeddedResource Include="schema.sql" />
    <EmbeddedResource Include="grants.sql" />
    <EmbeddedResource Include="upgrade-v2.sql" />
    <EmbeddedResource Include="upgrade-v3.sql" />
    <EmbeddedResource Include="upgrade-v4.sql" />
  </ItemGroup>
</Project>
