<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><Version>0.2.1-d1.3</Version></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Costina.Persistence/Costina.Persistence.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
  </ItemGroup>
</Project>
