<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting><Version>0.2.0-d1.2</Version>
    <AssemblyName>Costina.Desktop</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Costina.Client/Costina.Client.csproj" /></ItemGroup>
</Project>
